package com.footballadvisor.agent;

import com.footballadvisor.config.SpringContext;
import com.footballadvisor.dto.RecommendationResponse;
import com.footballadvisor.entity.PlayerEntity;
import com.footballadvisor.entity.TransferNeedEntity;
import com.footballadvisor.recommendation.RecommendationEngine;
import com.footballadvisor.recommendation.RecommendationScore;
import com.footballadvisor.repository.PlayerRepository;
import com.footballadvisor.service.RecommendationService;
import jade.core.Agent;
import jade.lang.acl.ACLMessage;

import java.math.BigDecimal;
import java.util.Comparator;
import java.util.List;

public class TransferRecommendationAgent extends Agent {

    @Override
    protected void setup() {
        System.out.println("TransferRecommendationAgent started.");

        addBehaviour(new jade.core.behaviours.CyclicBehaviour() {
            @Override
            public void action() {
                ACLMessage message = receive();

                if (message != null) {
                    String sender = message.getSender().getLocalName();

                    System.out.println("[ACL] TransferRecommendationAgent received from "
                            + sender
                            + " | "
                            + ACLMessage.getPerformative(message.getPerformative())
                            + " | "
                            + message.getContent());
                    AgentAclLogger.log(
                            sender,
                            getLocalName(),
                            message.getPerformative(),
                            message.getContent()
                    );

                    String recommendationResult = generateRecommendationResult(message.getContent());

                    ACLMessage reply = message.createReply();
                    reply.setPerformative(ACLMessage.INFORM);
                    reply.setContent(recommendationResult);
                    send(reply);
                    AgentAclLogger.log(
                            getLocalName(),
                            sender,
                            reply.getPerformative(),
                            reply.getContent()
                    );

                    System.out.println("[ACL] TransferRecommendationAgent -> "
                            + sender
                            + " | INFORM | "
                            + reply.getContent());
                } else {
                    block();
                }
            }
        });
    }

    private String generateRecommendationResult(String content) {
        try {
            Long transferNeedId = extractTransferNeedId(content);

            if (transferNeedId != null) {
                RecommendationService recommendationService =
                        SpringContext.getBean(RecommendationService.class);

                List<RecommendationResponse> recommendations =
                        recommendationService.generateRecommendations(transferNeedId)
                                .stream()
                                .limit(3)
                                .toList();

                return formatRecommendationResponses(recommendations);
            }

            return generateLegacyRecommendationResult(content);

        } catch (Exception ex) {
            return "Failed to generate recommendations: " + ex.getMessage();
        }
    }

    private Long extractTransferNeedId(String content) {
        String marker = "TransferNeedId:";

        if (content == null || !content.contains(marker)) {
            return null;
        }

        String value = content.substring(content.indexOf(marker) + marker.length()).trim();

        return Long.parseLong(value.split("\\s+")[0].trim());
    }

    private String formatRecommendationResponses(List<RecommendationResponse> recommendations) {
        if (recommendations.isEmpty()) {
            return "RecommendationService returned no eligible players.";
        }

        StringBuilder response = new StringBuilder(
                "Top transfer recommendations generated by RecommendationService:\n"
        );

        for (int i = 0; i < recommendations.size(); i++) {
            RecommendationResponse recommendation = recommendations.get(i);
            PlayerEntity player = recommendation.player();

            response.append(i + 1)
                    .append(". ")
                    .append(player.getName())
                    .append(" | Club: ")
                    .append(player.getCurrentClub())
                    .append(" | Position: ")
                    .append(player.getPosition())
                    .append(" | Total Score: ")
                    .append(String.format("%.2f", recommendation.totalScore()))
                    .append("%")
                    .append(" | Reasons: ")
                    .append(String.join(" / ", recommendation.reasons()))
                    .append("\n");
        }

        return response.toString();
    }

    private String generateLegacyRecommendationResult(String content) {
        String transferNeedData = extractLegacyTransferNeedData(content);
        String[] parts = transferNeedData.split("\\|");

        String neededPosition = parts[0].trim();
        String playingStyle = parts[1].trim();
        BigDecimal maxBudget = new BigDecimal(parts[2].trim());
        Integer maxAge = Integer.parseInt(parts[3].trim());

        TransferNeedEntity transferNeed = TransferNeedEntity.builder()
                .neededPosition(neededPosition)
                .playingStyle(playingStyle)
                .maxBudget(maxBudget)
                .maxAge(maxAge)
                .build();

        PlayerRepository playerRepository = SpringContext.getBean(PlayerRepository.class);
        RecommendationEngine recommendationEngine = SpringContext.getBean(RecommendationEngine.class);

        List<PlayerRecommendationResult> results = playerRepository.findAll()
                .stream()
                .map(player -> {
                    RecommendationScore score = recommendationEngine.calculate(transferNeed, player);
                    return new PlayerRecommendationResult(player, score);
                })
                .sorted(Comparator.comparing(
                        result -> result.score().getTotalScore(),
                        Comparator.reverseOrder()
                ))
                .limit(3)
                .toList();

        if (results.isEmpty()) {
            return "No players found in database.";
        }

        StringBuilder response = new StringBuilder("Top transfer recommendations:\n");

        for (int i = 0; i < results.size(); i++) {
            PlayerRecommendationResult result = results.get(i);
            PlayerEntity player = result.player();
            RecommendationScore score = result.score();

            response.append(i + 1)
                    .append(". ")
                    .append(player.getName())
                    .append(" | Position: ")
                    .append(player.getPosition())
                    .append(" | Age: ")
                    .append(player.getAge())
                    .append(" | Market Value: ")
                    .append(player.getMarketValue())
                    .append(" | Total Score: ")
                    .append(String.format("%.2f", score.getTotalScore()))
                    .append("%")
                    .append(" | Position Match: ")
                    .append(String.format("%.2f", score.getPositionMatch()))
                    .append("%")
                    .append(" | Style Match: ")
                    .append(String.format("%.2f", score.getStyleMatch()))
                    .append("%")
                    .append(" | Budget Match: ")
                    .append(String.format("%.2f", score.getBudgetMatch()))
                    .append("%")
                    .append(" | Age Match: ")
                    .append(String.format("%.2f", score.getAgeMatch()))
                    .append("%")
                    .append("\n");
        }

        return response.toString();
    }

    private String extractLegacyTransferNeedData(String content) {
        String marker = "TransferNeed:";

        if (!content.contains(marker)) {
            throw new IllegalArgumentException("TransferNeed data not found in ACL message.");
        }

        return content.substring(content.indexOf(marker) + marker.length()).trim();
    }

    private record PlayerRecommendationResult(
            PlayerEntity player,
            RecommendationScore score
    ) {
    }
}
