package com.footballadvisor.agent;

import com.footballadvisor.config.SpringContext;
import com.footballadvisor.dto.RecommendationResponse;
import com.footballadvisor.entity.PlayerEntity;
import com.footballadvisor.service.RecommendationService;
import jade.core.Agent;
import jade.lang.acl.ACLMessage;

import java.util.List;

public class TransferRecommendationAgent extends Agent {

    @Override
    protected void setup() {
        System.out.println("TransferRecommendationAgent started.");

        addBehaviour(new jade.core.behaviours.CyclicBehaviour() {
            @Override
            public void action() {
                ACLMessage message = receive();

                if (message != null) {
                    String sender = message.getSender().getLocalName();

                    System.out.println("[ACL] TransferRecommendationAgent received from "
                            + sender
                            + " | "
                            + ACLMessage.getPerformative(message.getPerformative())
                            + " | "
                            + message.getContent());
                    AgentAclLogger.log(
                            sender,
                            getLocalName(),
                            message.getPerformative(),
                            message.getContent()
                    );

                    String recommendationResult = generateRecommendationResult(message.getContent());

                    ACLMessage reply = message.createReply();
                    reply.setPerformative(ACLMessage.INFORM);
                    reply.setContent(recommendationResult);
                    send(reply);
                    AgentAclLogger.log(
                            getLocalName(),
                            sender,
                            reply.getPerformative(),
                            reply.getContent()
                    );

                    System.out.println("[ACL] TransferRecommendationAgent -> "
                            + sender
                            + " | INFORM | "
                            + reply.getContent());
                } else {
                    block();
                }
            }
        });
    }

    private String generateRecommendationResult(String content) {
        try {
            Long transferNeedId = extractTransferNeedId(content);

            RecommendationService recommendationService =
                    SpringContext.getBean(RecommendationService.class);

            List<RecommendationResponse> recommendations =
                    recommendationService.generateRecommendations(transferNeedId)
                            .stream()
                            .limit(3)
                            .toList();

            return formatRecommendationResponses(recommendations);

        } catch (Exception ex) {
            return "Failed to generate recommendations: " + ex.getMessage();
        }
    }

    private Long extractTransferNeedId(String content) {
        String marker = "TransferNeedId:";

        if (content == null || !content.contains(marker)) {
            throw new IllegalArgumentException("TransferNeedId not found in ACL message.");
        }

        String value = content.substring(content.indexOf(marker) + marker.length()).trim();

        return Long.parseLong(value.split("\\s+")[0].trim());
    }

    private String formatRecommendationResponses(List<RecommendationResponse> recommendations) {
        if (recommendations.isEmpty()) {
            return "RecommendationService returned no eligible players.";
        }

        StringBuilder response = new StringBuilder(
                "Top transfer recommendations generated by RecommendationService:\n"
        );

        for (int i = 0; i < recommendations.size(); i++) {
            RecommendationResponse recommendation = recommendations.get(i);
            PlayerEntity player = recommendation.player();

            response.append(i + 1)
                    .append(". ")
                    .append(player.getName())
                    .append(" | Club: ")
                    .append(player.getCurrentClub())
                    .append(" | Position: ")
                    .append(player.getPosition())
                    .append(" | Total Score: ")
                    .append(String.format("%.2f", recommendation.totalScore()))
                    .append("%")
                    .append(" | Reasons: ")
                    .append(String.join(" / ", recommendation.reasons()))
                    .append("\n");
        }

        return response.toString();
    }
}
